project_name: audiobait
dist: dist

release:
  github:
    owner: TheCacophonyProject
    name: audiobait
  name_template: '{{.Tag}}'

builds:
- goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
  main: ./cmd/audiobait
  ldflags: -s -w -X main.version={{.Version}}
  binary: audiobait

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

nfpms:
- vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Cacophony Developers <coredev@cacophony.org.nz>
  description: Play audio lures on a schedule
  license: GPL v3.0
  file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  dependencies:
    - sox
  bindir: /usr/bin
  files:
    "_release/audiobait.service": "/etc/systemd/system/audiobait.service"
  scripts:
      postinstall: "_release/postinstall.sh"
